import {
  number1,
  number2,
  number3,
  number4,
  number5,
  number6,
  number7,
  number8,
  number9,
  number10,
  number11,
  number12,
  number13,
  number14,
  number15,
  number16,
  number17,
  number18,
  number19,
  number20,
  number21,
  number22,
  number23,
  number24,
  number25,
  number26,
  number27,
  number28,
  number29,
  number30,
  number31,
} from '../assets/img/desktop/imageDesktop';

export const dataDesktop = [
  {
    id: 1,
    img: number1,
    title: 'Love Actually',
    genre: ['Romance', 'Comedy', 'Drama'],
    rating: 7.6,
  },
  {
    id: 2,
    img: number2,
    title: 'Shazam!',
    genre: ['Action', 'Comedy', 'Fantasy'],
    rating: 7.0,
  },
  {
    id: 3,
    img: number3,
    title: 'Avatar',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 7.9,
  },
  {
    id: 4,
    img: number4,
    title: 'Fast X',
    genre: ['Action', 'Crime', 'Thriller'],
    rating: 5.9,
  },
  {
    id: 5,
    img: number5,
    title: 'Blue Lock',
    genre: ['Animation', 'Sports', 'Drama'],
    rating: 8.4,
  },
  {
    id: 6,
    img: number6,
    title: 'The Little Mermaid',
    genre: ['Adventure', 'Family', 'Fantasy'],
    rating: 7.2,
  },
  {
    id: 7,
    img: number7,
    title: 'The Tomorrow War',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 6.5,
  },
  {
    id: 8,
    img: number8,
    title: 'Rio',
    genre: ['Animation', 'Adventure', 'Comedy'],
    rating: 6.9,
  },
  {
    id: 9,
    img: number9,
    title: 'A Man Called Otto',
    genre: ['Comedy', 'Drama'],
    rating: 7.5,
  },
  {
    id: 10,
    img: number10,
    title: 'Big Hero 6',
    genre: ['Animation', 'Action', 'Adventure'],
    rating: 7.8,
  },
  {
    id: 11,
    img: number11,
    title: 'Suzume',
    genre: ['Animation', 'Adventure', 'Fantasy'],
    rating: 7.9,
  },
  {
    id: 12,
    img: number12,
    title: 'Batman',
    genre: ['Action', 'Crime', 'Drama'],
    rating: 7.8,
  },
  {
    id: 13,
    img: number13,
    title: 'Stuart Little',
    genre: ['Animation', 'Comedy', 'Family'],
    rating: 6.0,
  },
  {
    id: 14,
    img: number14,
    title: 'Baymax',
    genre: ['Animation', 'Comedy', 'Family'],
    rating: 7.8,
  },
  {
    id: 15,
    img: number15,
    title: 'Missing',
    genre: ['Drama', 'Mystery', 'Thriller'],
    rating: 7.4,
  },
  {
    id: 16,
    img: number16,
    title: 'Guardians of the Galaxy',
    genre: ['Action', 'Adventure', 'Comedy'],
    rating: 8.0,
  },
  {
    id: 17,
    img: number17,
    title: 'All Of Us Are Dead',
    genre: ['Action', 'Drama', 'Horror'],
    rating: 7.5,
  },
  {
    id: 18,
    img: number18,
    title: 'Alice in Borderland',
    genre: ['Action', 'Drama', 'Sci-Fi'],
    rating: 8.2,
  },
  {
    id: 19,
    img: number19,
    title: 'Missing',
    genre: ['Drama', 'Mystery', 'Thriller'],
    rating: 7.4,
  },
  {
    id: 20,
    img: number20,
    title: 'M3GAN',
    genre: ['Horror', 'Sci-Fi', 'Thriller'],
    rating: 6.5,
  },
  {
    id: 21,
    img: number21,
    title: 'Jurassic World: Dominion',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 5.6,
  },
  {
    id: 22,
    img: number22,
    title: 'Dilan 1991',
    genre: ['Drama', 'Romance'],
    rating: 6.2,
  },
  {
    id: 23,
    img: number23,
    title: 'Sonic the Hedgehog 2',
    genre: ['Action', 'Adventure', 'Comedy'],
    rating: 6.5,
  },
  {
    id: 24,
    img: number24,
    title: 'Spider-Man: Across the Spider-Verse',
    genre: ['Animation', 'Action', 'Adventure'],
    rating: 8.7,
  },
  {
    id: 25,
    img: number25,
    title: 'Ant-Man and the Wasp: Quantumania',
    genre: ['Action', 'Adventure', 'Comedy'],
    rating: 6.1,
  },
  {
    id: 26,
    img: number26,
    title: 'My Hero Academia: World Heroes’ Mission',
    genre: ['Animation', 'Action', 'Adventure'],
    rating: 7.3,
  },
  {
    id: 27,
    img: number27,
    title: 'Doctor Strange',
    genre: ['Action', 'Adventure', 'Fantasy'],
    rating: 7.5,
  },
  {
    id: 28,
    img: number28,
    title: 'Black Adam',
    genre: ['Action', 'Fantasy', 'Sci-Fi'],
    rating: 6.2,
  },
  {
    id: 29,
    img: number29,
    title: 'The Devil All The Time',
    genre: ['Crime', 'Drama', 'Thriller'],
    rating: 7.1,
  },
  {
    id: 30,
    img: number30,
    title: 'Ted Lasso',
    genre: ['Comedy', 'Drama', 'Sport'],
    rating: 8.8,
  },
  {
    id: 31,
    img: number31,
    title: "Don't Look Up",
    genre: ['Comedy', 'Drama', 'Sci-Fi'],
    rating: 7.2,
  },
];
