import {
  number1,
  number2,
  number3,
  number4,
  number5,
  number6,
  number7,
  number8,
  number9,
  number10,
  number11,
  number12,
  number13,
  number14,
  number15,
  number16,
  number17,
  number18,
  number19,
  number20,
  number21,
  number22,
  number23,
  number24,
  number25,
  number26,
  number27,
  number28,
  number29,
  number30,
  number31,
} from '../assets/img/films/imageFilms';

export const dataFilms = [
  {
    id: 1,
    img: number1,
    title: 'Love Actually',
    subTitle: 'Film',
    genre: ['Romance', 'Comedy', 'Drama'],
    onGoing: true,
    rating: '7.6',
  },
  {
    id: 2,
    img: number2,
    title: 'Shazam!',
    subTitle: 'Film',
    genre: ['Action', 'Comedy', 'Fantasy'],
    ongGoing: false,
    rating: '7.0',
  },
  {
    id: 3,
    img: number3,
    title: 'Avatar',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    subTitle: 'Film',
    onGoing: false,
    rating: '7.9',
  },
  {
    id: 4,
    img: number4,
    title: 'Fast X',
    genre: ['Action', 'Crime', 'Thriller'],
    subTitle: 'Film',
    onGoing: false,
    rating: '5.9',
  },
  {
    id: 5,
    img: number5,
    title: 'Blue Lock',
    subTitle: '24 Episode',
    genre: ['Animation', 'Sports', 'Drama'],
    onGoing: true,
    rating: '8.4',
  },
  {
    id: 6,
    img: number6,
    title: 'The Little Mermaid',
    subTitle: 'Film',
    genre: ['Adventure', 'Family', 'Fantasy'],
    onGoing: false,
    rating: '7.2',
  },
  {
    id: 7,
    img: number7,
    title: 'The Tomorrow War',
    subTitle: 'Film',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    onGoing: false,
    rating: '6.5',
  },
  {
    id: 8,
    img: number8,
    title: 'Batman',
    genre: ['Action', 'Adventure', 'Thriller'],
    subTitle: 'Film',
    onGoing: false,
    rating: '6.9',
  },
  {
    id: 9,
    img: number9,
    title: 'All of Us Are Dead',
    subTitle: 'Film',
    genre: ['Comedy', 'Drama'],
    onGoing: false,
    rating: '7.5',
  },
  {
    id: 10,
    img: number10,
    title: 'A man Called Otto',
    subTitle: 'Film',
    genre: ['Animation', 'Action', 'Adventure'],
    onGoing: false,
    rating: '7.8',
  },
  {
    id: 11,
    img: number11,
    title: 'Alice in Borderland',
    subTitle: 'Film',
    genre: ['Action', 'Adventure', 'Game'],
    onGoing: false,
    rating: '7.9',
  },
  {
    id: 12,
    img: number12,
    title: 'Big Hero 6',
    subTitle: 'Film',
    genre: ['Animation', 'Action', 'Adventure'],
    onGoing: false,
    rating: '7.8',
  },
  {
    id: 13,
    img: number13,
    title: 'Missing',
    subTitle: 'Film',
    genre: ['Animation', 'Comedy', 'Family'],
    onGoing: false,
    rating: '6.0',
  },
  {
    id: 14,
    img: number14,
    title: 'Suzume',
    genre: ['Animation', 'Comedy', 'Family'],
    subTitle: 'Film',
    onGoing: false,
    rating: '7.8',
  },
  {
    id: 15,
    img: number15,
    title: 'Megan',
    genre: ['Drama', 'Mystery', 'Thriller'],
    subTitle: 'Film',
    onGoing: false,
    rating: '7.4',
  },
  {
    id: 16,
    img: number16,
    title: 'Quantumania',
    subTitle: 'Film',
    genre: ['Action', 'Adventure', 'Comedy'],
    onGoing: false,
    rating: '8.0',
  },
  {
    id: 17,
    img: number17,
    title: 'Duty Ater School',
    subTitle: 'Film',
    genre: ['Action', 'Drama', 'School'],
    onGoing: false,
    rating: '7.5',
  },
  {
    id: 18,
    img: number18,
    title: 'My Hero Academia: World Heroes Mission',
    subTitle: '24 Episode',
    genre: ['Action', 'Animation', 'Sci-Fi'],
    onGoing: true,
    rating: '8.2',
  },
  {
    id: 19,
    img: number19,
    title: 'Doctor Strange in the Multiverse of Madness',
    subTitle: 'Film',
    genre: ['Drama', 'Mystery', 'Thriller'],
    onGoing: false,
    rating: '7.4',
  },
  {
    id: 20,
    img: number20,
    title: 'Dont Look Up',
    subTitle: 'Film',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    onGoing: false,
    rating: '6.5',
  },
  {
    id: 21,
    img: number21,
    title: 'Black Adam',
    subTitle: 'Film',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    onGoing: false,
    rating: '5.6',
  },
  {
    id: 22,
    img: number22,
    title: 'Devil All The Time',
    subTitle: 'Film',
    genre: ['Action', 'Crime', 'Drama'],
    onGoing: false,
    rating: '6.2',
  },
  {
    id: 23,
    img: number23,
    title: 'Ted Lasso',
    subTitle: 'Film',
    genre: ['TV', 'Show', 'Comedy'],
    onGoing: false,
    rating: '6.5',
  },
  {
    id: 24,
    img: number24,
    title: 'Stuart Little',
    subTitle: 'Film',
    genre: ['Animation', 'Action', 'Adventure'],
    onGoing: false,
    rating: '8.7',
  },
  {
    id: 25,
    img: number25,
    title: 'Jurassic Park Dominion',
    subTitle: 'Film',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    onGoing: false,
    rating: '6.1',
  },
  {
    id: 26,
    img: number26,
    title: 'Baymax',
    genre: ['Animation', 'Action', 'Adventure'],
    subTitle: 'Film',
    onGoing: false,
    rating: '7.3',
  },
  {
    id: 27,
    img: number27,
    title: 'Dilan 1991',
    subTitle: 'Film',
    genre: ['Action', 'Drama', 'Romance'],
    onGoing: false,
    rating: '7.5',
  },
  {
    id: 28,
    img: number28,
    title: 'Happiness',
    subTitle: 'Film',
    genre: ['Action', 'Fantasy', 'Sci-Fi'],
    onGoing: false,
    rating: '6.2',
  },
  {
    id: 29,
    img: number29,
    title: 'Sonic 2',
    subTitle: 'Film',
    genre: ['Animation', 'Action', 'Thriller'],
    onGoing: false,
    rating: '7.1',
  },
  {
    id: 30,
    img: number30,
    title: 'Guardian of the Galaxy',
    subTitle: 'Film',
    genre: ['Comedy', 'Action', 'Sci-Fi'],
    onGoing: false,
    rating: '8.8',
  },
  {
    id: 31,
    img: number31,
    title: 'Spiderman: Across the Spider-Verse',
    subTitle: 'Film',
    genre: ['Animation', 'Drama', 'Sci-Fi'],
    onGoing: false,
    rating: '7.2',
  },
];
